language: php

cache:
  directories:
    - $HOME/.composer/cache

php:
    - '5.4'
    - '5.5'
    - '5.6'
    - '7.0'
    - '7.1'
    - hhvm

matrix:
    fast_finish: true
    include:
        - php: '7.1'
          env: 'COMPOSER_FLAGS=--prefer-lowest'

before_install:
    - phpenv config-rm xdebug.ini || echo "xdebug not available"

install:
    - composer update $COMPOSER_FLAGS --no-interaction --prefer-dist --no-progress --no-suggest --ansi

script:
    - vendor/bin/phpunit
